def menu_calculadora():
    print("\n-------------------------------------")
    print("-                                   -")
    print("- Bem-vindo à calculadora em Python -")
    print("-          by Igor Leon             -")
    print("-                                   -")
    print("-------------------------------------")
    print("-       1 - Adição                  -")
    print("-       2 - Subtração               -")
    print("-       3 - Multiplicação           -")
    print("-       4 - Divisão                 -")
    print("-       5 - Sair                    -")
    print("-------------------------------------")

def menu_Estoque():
    print("\n--------------------------")
    print("-   Estoque  em Python   -")
    print("-     by: Igor Leon      -")
    print("-                        -")
    print("-   1 - Inserir Produto  -")
    print("-   2 - Ver Estoque      -")
    print("-   3 - Atualizar        -")
    print("-   4 - Excluír          -")
    print("-                        -")
    print("--------------------------")

def menu_Cliente():
    print("\n----------------------------------")
    print("-   Lista de Clientes  em Python   -")
    print("-     by: Igor Leon                -")
    print("-                                  -")
    print("-   1 - Inserir Cliente            -")
    print("-   2 - Inserir Veiculo            -")
    print("-   3 - Ver Clientes               -")
    print("-   4 - Atualizar Cliente          -")
    print("-   5 - Excluír Cliente            -")
    print("-                                  -")
    print("------------------------------------")